version: '3.9'

services:
  web:
    build: .
    container_name: smartdoc_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: smartdoc_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: smartdoc
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpass

volumes:
  postgres_data:

